apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: client
spec:
  containers:
    - image: ubuntu:latest
      name: test
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep infinity']
    - image: nginx:1.13
      name: nginx
      ports:
      - containerPort: 80
